# Configuration file for Beckhoff EL2008
 vendor_id: 0x00000002
 product_id: 0x07d83052
 rpdo:  # RxPDO
   - index: 0x1a00
     channels:
       - {index: 0x6000, sub_index: 1, type: bool, mask: 1, command_interface: d_output.1}
   - index: 0x1a01
     channels:
       - {index: 0x6010, sub_index: 1, type: bool}
   - index: 0x1a02
     channels:
       - {index: 0x6020, sub_index: 1, type: bool}
   - index: 0x1a03
     channels:
       - {index: 0x6030, sub_index: 1, type: bool, mask: 8, command_interface: d_output.4}
   - index: 0x1a04
     channels:
       - {index: 0x6040, sub_index: 1, type: bool}
   - index: 0x1a05
     channels:
       - {index: 0x6050, sub_index: 1, type: bool}
   - index: 0x1a06
     channels:
       - {index: 0x6060, sub_index: 1, type: bool}
   - index: 0x1a07
     channels:
       - {index: 0x6070, sub_index: 1, type: bool}
 sm:  # Sync Manager
   - {index: 0, type: output, pdo: rpdo, watchdog: enable}