# Configuration file for Beckhoff EL5101
vendor_id: 0x00000002
product_id: 0x13ed3052
rpdo:  # RxPDO
  - index: 0x1600
    channels:
      - {index: 0x7000, sub_index: 0x01, type: uint8, command_interface: ctrl_word}
      - {index: 0x7000, sub_index: 0x02, type: int16, command_interface: value}
tpdo:  # TxPDO
  - index: 0x1a00
    channels:
      - {index: 0x6000, sub_index: 0x01, type: uint8, state_interface: status_word}
      - {index: 0x6000, sub_index: 0x02, type: int16, state_interface: value}
      - {index: 0x6000, sub_index: 0x03, type: int16, state_interface: latch_value}
sm:  # Sync Manager
  - {index: 0, type: output, pdo: ~, watchdog: disable}
  - {index: 1, type: input, pdo: ~, watchdog: disable}
  - {index: 2, type: output, pdo: rpdo, watchdog: disable}
  - {index: 3, type: input, pdo: tpdo, watchdog: disable}