# Configuration file for Beckhoff EL4132
vendor_id: 0x00000002
product_id: 0x10243052
rpdo:  # RxPDO
  - index: 0x1600
    channels:
      - {index: 0x3001, sub_index: 1, type: int16, command_interface: analog_output.1}
  - index: 0x1601
    channels:
      - {index: 0x3002, sub_index: 1, type: int16, command_interface: analog_output.2}
sm:  # Sync Manager
  - {index: 0, type: output, pdo: ~, watchdog: disable}
  - {index: 1, type: input, pdo: ~, watchdog: disable}
  - {index: 2, type: output, pdo: rpdo, watchdog: disable}
  - {index: 3, type: input, pdo: ~, watchdog: disable}