controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    gpio_controller:
      type: gpio_controllers/GpioCommandController


gpio_controller:
  ros__parameters:
    gpios:
      - gpio_0
      - gpio_1
      - gpio_2
    command_interfaces:
      gpio_0:
        - ctrl
        - position
        - latch_value
        - status
        - value
      gpio_1:
        - analog_output.1
        - analog_output.2
      gpio_2:
        - analog_input.1
        - analog_input.2        
    state_interfaces:
      gpio_0:
        - ctrl
        - position
        - latch_value
        - status
        - value
      gpio_1:
        - analog_output.1
        - analog_output.2
      gpio_2:
        - analog_input.1
        - analog_input.2
        
        
        
 